apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: mlflow-config
            - secretRef:
                name: mlflow-secrets
